from fastapi import APIRouter
from app.api.v1.endpoints import auth, trainings, enrollments, instructor, admin, certificates, onboarding, course_content, content_progress, course_completion, modules, lessons, content_items, assessments, attendance, progress, completion, notifications, reports, support, payments, comments

api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(comments.router, prefix="/comments", tags=["comments"])
api_router.include_router(trainings.router, prefix="/trainings", tags=["trainings"])
api_router.include_router(enrollments.router, prefix="/enrollments", tags=["enrollments"])
api_router.include_router(instructor.router, prefix="/instructor", tags=["instructor"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(certificates.router, prefix="/certificates", tags=["certificates"])
api_router.include_router(onboarding.router, prefix="/onboarding", tags=["onboarding"])
api_router.include_router(course_content.router, prefix="/course-content", tags=["course-content"])
api_router.include_router(content_progress.router, prefix="/content-progress", tags=["content-progress"])
api_router.include_router(course_completion.router, prefix="/course-completion", tags=["course-completion"])
api_router.include_router(modules.router, prefix="/modules", tags=["Modules"])
api_router.include_router(lessons.router, prefix="/lessons", tags=["Lessons"])
api_router.include_router(content_items.router, prefix="/content-items", tags=["Content Items"])
api_router.include_router(assessments.router, prefix="/assessments", tags=["Assessments"])
api_router.include_router(attendance.router, prefix="/attendance", tags=["attendance"])
api_router.include_router(progress.router, prefix="/progress", tags=["progress"])
api_router.include_router(completion.router, prefix="/completion", tags=["completion"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(support.router, prefix="/support", tags=["support"])
api_router.include_router(payments.router, prefix="/payments", tags=["payments"])