"""add video_url flyer_url columns

Revision ID: 1266562e3ffe
Revises: d63db8b50949
Create Date: 2026-03-22 20:13:19.122549

"""
from alembic import op
import sqlalchemy as sa


revision = '1266562e3ffe'
down_revision = 'd63db8b50949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('trainings', sa.Column('flyer_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'flyer_url')
    op.drop_column('trainings', 'video_url')
    # ### end Alembic commands ###
