"""add video_url and flyer_url to trainings

Revision ID: d63db8b50949
Revises: 
Create Date: 2026-03-22 20:09:51.191062

"""
from alembic import op
import sqlalchemy as sa


revision = 'd63db8b50949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='unique')
    # ### end Alembic commands ###
